name: Tests Manual

on:
  workflow_dispatch:
    inputs:
      ref1:
        description: 'Branch name, tag, or commit SHA #1'
        required: true
      ref2:
        description: 'Branch name, tag, or commit SHA #2'
        required: true
      leader_name:
        description: 'Leader name for ITs (auto selected if empty)'
        required: false
        default: ''

# The ref parameter in actions/checkout is flexible and can accept:
# Branch names (e.g., main)
# Tag names (e.g., v1.2.3)
# Full commit SHAs (e.g., a1b2c3d4)

jobs:
  get_dependencies:
    name: "Dependencies"
    uses: ./.github/workflows/dependencies.yaml

  build1:
    name: "Build ref ${{ github.event.inputs.ref1 }}"
    needs: get_dependencies
    uses: ./.github/workflows/build-ubuntu.yaml
    with:
      ref: ${{ github.event.inputs.ref1 }}
      target: "all"
  
  build2:
    name: "Build ref ${{ github.event.inputs.ref2 }}"
    needs: get_dependencies
    uses: ./.github/workflows/build-ubuntu.yaml
    with:
      ref: ${{ github.event.inputs.ref2 }}
      target: "all"

  integration_tests_ubuntu:
    name: IT [${{ matrix.cluster }}/${{ matrix.mode }}/${{ matrix.consistency }}]
    strategy:
      matrix:
        mode: ["fsm_mode"]
        cluster: ["multi3"]
        consistency: ["strong_consistency"]
      fail-fast: false
    runs-on: ubuntu-latest
    needs: 
      - build1
      - build2
    env:
        RUN_UID: ${{ matrix.cluster }}_${{ matrix.mode }}_${{ matrix.consistency }}
    steps:    
      - name: Checkout repo1
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref1 }}
          path: repo1
          fetch-depth: 0

      - name: Checkout repo2
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref2 }}
          path: repo2
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          path: ./repo1
          name: ${{needs.build1.outputs.cache_key }}
      - uses: actions/download-artifact@v4
        with:
          path: ./repo2
          name: ${{needs.build2.outputs.cache_key }}

        # Set execution permissions for all .tsk 
        # which were lost when the artifact was created
      - name: Chmod all .tsk
        working-directory: repo1
        run: find ./build -type f -name "*.tsk" -exec chmod +x {} +
      - name: Chmod all .tsk
        working-directory: repo2
        run: find ./build -type f -name "*.tsk" -exec chmod +x {} +

      - name: Run Integration Tests
        working-directory: repo2
        env:
          BLAZINGMQ_LEADER_NAME: "${{ github.event.inputs.leader_name }}" 
          
          BLAZINGMQ_BROKER_EAST1: "${{ github.workspace }}/repo1/build/blazingmq/src/applications/bmqbrkr/bmqbrkr.tsk"
          BLAZINGMQ_BROKER_EAST2: "${{ github.workspace }}/repo1/build/blazingmq/src/applications/bmqbrkr/bmqbrkr.tsk"
          BLAZINGMQ_BROKER_WEST1: "${{ github.workspace }}/repo1/build/blazingmq/src/applications/bmqbrkr/bmqbrkr.tsk"
          BLAZINGMQ_BROKER_WEST2: "${{ github.workspace }}/repo1/build/blazingmq/src/applications/bmqbrkr/bmqbrkr.tsk"
          BLAZINGMQ_BROKER_NEW_VERSION: "${{ github.workspace }}/repo2/build/blazingmq/src/applications/bmqbrkr/bmqbrkr.tsk"
        run: |
          pip install -r ./src/python/requirements.txt

          ./src/integration-tests/run-tests \
            "${{ matrix.mode }} and ${{ matrix.cluster }} and ${{ matrix.consistency }}" \
            --log-level ERROR                   \
            --log-file-level=info               \
            --bmq-tolerate-dirty-shutdown       \
            --bmq-log-dir=failure-logs          \
            --bmq-log-level=INFO                \
            --junitxml=integration-tests.xml    \
            --tb long                           \
            --reruns=3                          \
            -n logical -v

      - name: Upload failure-logs as artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_id }}_failure_logs_${{ env.RUN_UID }}
          path: ${{ github.workspace }}/repo2/src/integration-tests/failure-logs
          retention-days: 5
