name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      ref1:
        description: 'Branch name, tag, or commit SHA #1'
        required: true
      ref2:
        description: 'Branch name, tag, or commit SHA #2'
        required: true

# The ref parameter in actions/checkout is flexible and can accept:
# Branch names (e.g., main)
# Tag names (e.g., v1.2.3)
# Full commit SHAs (e.g., a1b2c3d4)

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ref: ${{ github.event.inputs.ref1 }}
            folder: repo1
          - ref: ${{ github.event.inputs.ref2 }}
            folder: repo2

    steps:    
    - name: Checkout ${{ matrix.ref }}
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: ${{ matrix.ref }}
        path: ${{ matrix.folder }}
        fetch-depth: 0

    - name: Show commit hash for ${{ matrix.ref }}
      working-directory: ${{ matrix.folder }}
      run: |
        git rev-parse HEAD


